#!/usr/bin/env python3
"""Generate ``languages/yaml/injections.scm`` for the Zed extension.

This is the Zed equivalent of the TypeScript ``src/generate.ts`` used by the
original VS Code extension. It produces a tree-sitter injection query file
that adds syntax-highlighting injections for every supported embedded
language, triggered by the two marker forms described in the README:

* inline marker   - ``key: | # <lang>`` / ``key: > # <lang>``
* block-wide marker - ``# yaml-embedded-languages: <lang>``
"""

from __future__ import annotations

import re
from pathlib import Path

# Mapping of identifier (used in the YAML comment marker) to the Zed
# language name that should be injected. The identifiers match those
# accepted by the original VS Code extension. See ``src/constants.ts``
# for the original TextMate scope names.
#
# Identifiers are sorted alphabetically to mirror ``src/constants.ts``.
LANGUAGES: dict[str, str] = {
    "bat": "Batch",
    "bibtex": "BibTeX",
    "c": "C",
    "c#": "C#",
    "c\\+\\+": "C++",
    "clojure": "Clojure",
    "coffee": "CoffeeScript",
    "cpp": "C++",
    "csharp": "C#",
    "css": "CSS",
    "cuda": "CUDA",
    "dart": "Dart",
    "diff": "Diff",
    "dockercompose": "YAML",
    "dockerfile": "Dockerfile",
    "f#": "F#",
    "fsharp": "F#",
    "go": "Go",
    "groovy": "Groovy",
    "handlebars": "Handlebars",
    "hlsl": "HLSL",
    "html": "HTML",
    "ini": "INI",
    "jade": "Pug",
    "java": "Java",
    "javascript": "JavaScript",
    "js": "JavaScript",
    "json": "JSON",
    "jsonc": "JSONC",
    "jsonl": "JSON",
    "jsx": "JSX",
    "julia": "Julia",
    "latex": "LaTeX",
    "less": "LESS",
    "log": "Log",
    "lua": "Lua",
    "make": "Makefile",
    "makefile": "Makefile",
    "markdown": "Markdown",
    "math": "Markdown",
    "objc": "Objective-C",
    "objcpp": "Objective-C++",
    "perl": "Perl",
    "php": "PHP",
    "pip": "Pip Requirements",
    "powerfx": "JavaScript",
    "powershell": "PowerShell",
    "properties": "Properties",
    "py": "Python",
    "python": "Python",
    "r": "R",
    "raku": "Raku",
    "razor": "Razor",
    "regex": "Regex",
    "requirements": "Pip Requirements",
    "rst": "reStructuredText",
    "ruby": "Ruby",
    "rust": "Rust",
    "scss": "SCSS",
    "shaderlab": "ShaderLab",
    "shell": "Shell Script",
    "sql": "SQL",
    "swift": "Swift",
    "tex": "TeX",
    "ts": "TypeScript",
    "tsx": "TSX",
    "typescript": "TypeScript",
    "vb": "Visual Basic",
    "xml": "XML",
    "xsl": "XSL",
    "yaml": "YAML",
}

HEADER = """\
; This file is auto-generated by ``generate.py`` in the repository root.
; Do not edit by hand; edit the ``LANGUAGES`` table in ``generate.py`` and
; re-run ``python3 generate.py``.
;
; Injection queries for embedded languages inside YAML block-scalars.
; Two marker forms are supported (see README.md):
;
;   1. Inline marker on the block-scalar line:
;
;         example: | # <lang>
;           highlighted
;
;   2. Block-wide marker placed before a mapping entry, which applies to
;      the immediately-following block-scalar value:
;
;         # yaml-embedded-languages: <lang>
;         example: |
;           highlighted
;
; The set of accepted ``<lang>`` identifiers is enumerated below, matching
; the set supported by the original VS Code extension.

; -- Base injections (kept in sync with Zed's built-in YAML grammar) ---------

((comment) @injection.content
  (#set! injection.language "comment"))

; GitHub Actions: inject JavaScript for ``actions/github-script`` steps.
(block_mapping
  (block_mapping_pair
    key: (flow_node) @_uses
    (#eq? @_uses "uses")
    value: (flow_node) @_actions_ghs
    (#match? @_actions_ghs "^actions/github-script"))
  (block_mapping_pair
    key: (flow_node) @_with
    (#eq? @_with "with")
    value: (block_node
      (block_mapping
        (block_mapping_pair
          key: (flow_node) @_run
          (#eq? @_run "script")
          value: [
            (flow_node
              (plain_scalar
                (string_scalar) @injection.content))
            (block_node
              (block_scalar) @injection.content)
          ]
          (#set! injection.language "javascript"))))))

; -- Embedded-language injections -------------------------------------------
"""


def _q(value: str) -> str:
    """Quote ``value`` as a tree-sitter string literal (double-quoted)."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _inline_template(marker_regex: str, language: str) -> str:
    """Query for ``key: | # <lang>`` (comment on the same line as the scalar)."""
    return (
        "((comment) @_marker\n"
        "  .\n"
        "  (block_scalar) @injection.content\n"
        f"  (#match? @_marker {_q(marker_regex)})\n"
        f"  (#set! injection.language {_q(language)}))\n"
    )


def _block_wide_template(marker_regex: str, language: str) -> str:
    """Query for ``# yaml-embedded-languages: <lang>`` preceding a pair."""
    return (
        "((comment) @_marker\n"
        "  .\n"
        "  (block_mapping_pair\n"
        "    value: (block_node\n"
        "      (block_scalar) @injection.content))\n"
        f"  (#match? @_marker {_q(marker_regex)})\n"
        f"  (#set! injection.language {_q(language)}))\n"
    )


def _inline_regex(identifier: str) -> str:
    # ``identifier`` already contains regex meta-characters where relevant
    # (matching the keys of the original ``LANGUAGES`` table). Tree-sitter
    # uses Rust-regex syntax, so ``\s`` etc. work out of the box.
    return f"^#\\s*{identifier}\\s*$"


def _block_wide_regex(identifier: str) -> str:
    return f"^#\\s*yaml-embedded-languages\\s*:\\s*{identifier}\\s*$"


def _render() -> str:
    parts: list[str] = [HEADER]
    for identifier, language in LANGUAGES.items():
        parts.append(f"\n; {identifier} -> {language}\n")
        parts.append(_inline_template(_inline_regex(identifier), language))
        parts.append("\n")
        parts.append(_block_wide_template(_block_wide_regex(identifier), language))
    return "".join(parts)


def _sanity_check(text: str) -> None:
    opens = text.count("(")
    closes = text.count(")")
    if opens != closes:
        raise SystemExit(
            f"injections.scm has unbalanced parentheses: {opens} '(' vs {closes} ')'"
        )
    # Make sure every rule ends with a newline and nothing else is stray.
    if not re.search(r"\)\)\s*\Z", text):
        raise SystemExit("injections.scm does not end with a closing ')'")


def main() -> None:
    root = Path(__file__).resolve().parent
    out = root / "languages" / "yaml" / "injections.scm"
    out.parent.mkdir(parents=True, exist_ok=True)
    text = _render()
    _sanity_check(text)
    out.write_text(text)
    print(f"Wrote {out.relative_to(root)} ({len(LANGUAGES)} languages)")


if __name__ == "__main__":
    main()
