; This file is auto-generated by ``generate.py`` in the repository root.
; Do not edit by hand; edit the ``LANGUAGES`` table in ``generate.py`` and
; re-run ``python3 generate.py``.
;
; Injection queries for embedded languages inside YAML block-scalars.
; Two marker forms are supported (see README.md):
;
;   1. Inline marker on the block-scalar line:
;
;         example: | # <lang>
;           highlighted
;
;   2. Block-wide marker placed before a mapping entry, which applies to
;      the immediately-following block-scalar value:
;
;         # yaml-embedded-languages: <lang>
;         example: |
;           highlighted
;
; The set of accepted ``<lang>`` identifiers is enumerated below, matching
; the set supported by the original VS Code extension.

; -- Base injections (kept in sync with Zed's built-in YAML grammar) ---------

((comment) @injection.content
  (#set! injection.language "comment"))

; GitHub Actions: inject JavaScript for ``actions/github-script`` steps.
(block_mapping
  (block_mapping_pair
    key: (flow_node) @_uses
    (#eq? @_uses "uses")
    value: (flow_node) @_actions_ghs
    (#match? @_actions_ghs "^actions/github-script"))
  (block_mapping_pair
    key: (flow_node) @_with
    (#eq? @_with "with")
    value: (block_node
      (block_mapping
        (block_mapping_pair
          key: (flow_node) @_run
          (#eq? @_run "script")
          value: [
            (flow_node
              (plain_scalar
                (string_scalar) @injection.content))
            (block_node
              (block_scalar) @injection.content)
          ]
          (#set! injection.language "javascript"))))))

; -- Embedded-language injections -------------------------------------------

; bat -> Batch
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*bat\\s*$")
  (#set! injection.language "Batch"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*bat\\s*$")
  (#set! injection.language "Batch"))

; bibtex -> BibTeX
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*bibtex\\s*$")
  (#set! injection.language "BibTeX"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*bibtex\\s*$")
  (#set! injection.language "BibTeX"))

; c -> C
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*c\\s*$")
  (#set! injection.language "C"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*c\\s*$")
  (#set! injection.language "C"))

; c# -> C#
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*c#\\s*$")
  (#set! injection.language "C#"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*c#\\s*$")
  (#set! injection.language "C#"))

; c\+\+ -> C++
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*c\\+\\+\\s*$")
  (#set! injection.language "C++"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*c\\+\\+\\s*$")
  (#set! injection.language "C++"))

; clojure -> Clojure
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*clojure\\s*$")
  (#set! injection.language "Clojure"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*clojure\\s*$")
  (#set! injection.language "Clojure"))

; coffee -> CoffeeScript
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*coffee\\s*$")
  (#set! injection.language "CoffeeScript"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*coffee\\s*$")
  (#set! injection.language "CoffeeScript"))

; cpp -> C++
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*cpp\\s*$")
  (#set! injection.language "C++"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*cpp\\s*$")
  (#set! injection.language "C++"))

; csharp -> C#
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*csharp\\s*$")
  (#set! injection.language "C#"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*csharp\\s*$")
  (#set! injection.language "C#"))

; css -> CSS
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*css\\s*$")
  (#set! injection.language "CSS"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*css\\s*$")
  (#set! injection.language "CSS"))

; cuda -> CUDA
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*cuda\\s*$")
  (#set! injection.language "CUDA"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*cuda\\s*$")
  (#set! injection.language "CUDA"))

; dart -> Dart
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*dart\\s*$")
  (#set! injection.language "Dart"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*dart\\s*$")
  (#set! injection.language "Dart"))

; diff -> Diff
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*diff\\s*$")
  (#set! injection.language "Diff"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*diff\\s*$")
  (#set! injection.language "Diff"))

; dockercompose -> YAML
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*dockercompose\\s*$")
  (#set! injection.language "YAML"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*dockercompose\\s*$")
  (#set! injection.language "YAML"))

; dockerfile -> Dockerfile
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*dockerfile\\s*$")
  (#set! injection.language "Dockerfile"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*dockerfile\\s*$")
  (#set! injection.language "Dockerfile"))

; f# -> F#
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*f#\\s*$")
  (#set! injection.language "F#"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*f#\\s*$")
  (#set! injection.language "F#"))

; fsharp -> F#
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*fsharp\\s*$")
  (#set! injection.language "F#"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*fsharp\\s*$")
  (#set! injection.language "F#"))

; go -> Go
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*go\\s*$")
  (#set! injection.language "Go"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*go\\s*$")
  (#set! injection.language "Go"))

; groovy -> Groovy
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*groovy\\s*$")
  (#set! injection.language "Groovy"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*groovy\\s*$")
  (#set! injection.language "Groovy"))

; handlebars -> Handlebars
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*handlebars\\s*$")
  (#set! injection.language "Handlebars"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*handlebars\\s*$")
  (#set! injection.language "Handlebars"))

; hlsl -> HLSL
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*hlsl\\s*$")
  (#set! injection.language "HLSL"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*hlsl\\s*$")
  (#set! injection.language "HLSL"))

; html -> HTML
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*html\\s*$")
  (#set! injection.language "HTML"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*html\\s*$")
  (#set! injection.language "HTML"))

; ini -> INI
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*ini\\s*$")
  (#set! injection.language "INI"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*ini\\s*$")
  (#set! injection.language "INI"))

; jade -> Pug
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*jade\\s*$")
  (#set! injection.language "Pug"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*jade\\s*$")
  (#set! injection.language "Pug"))

; java -> Java
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*java\\s*$")
  (#set! injection.language "Java"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*java\\s*$")
  (#set! injection.language "Java"))

; javascript -> JavaScript
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*javascript\\s*$")
  (#set! injection.language "JavaScript"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*javascript\\s*$")
  (#set! injection.language "JavaScript"))

; js -> JavaScript
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*js\\s*$")
  (#set! injection.language "JavaScript"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*js\\s*$")
  (#set! injection.language "JavaScript"))

; json -> JSON
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*json\\s*$")
  (#set! injection.language "JSON"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*json\\s*$")
  (#set! injection.language "JSON"))

; jsonc -> JSONC
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*jsonc\\s*$")
  (#set! injection.language "JSONC"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*jsonc\\s*$")
  (#set! injection.language "JSONC"))

; jsonl -> JSON
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*jsonl\\s*$")
  (#set! injection.language "JSON"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*jsonl\\s*$")
  (#set! injection.language "JSON"))

; jsx -> JSX
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*jsx\\s*$")
  (#set! injection.language "JSX"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*jsx\\s*$")
  (#set! injection.language "JSX"))

; julia -> Julia
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*julia\\s*$")
  (#set! injection.language "Julia"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*julia\\s*$")
  (#set! injection.language "Julia"))

; latex -> LaTeX
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*latex\\s*$")
  (#set! injection.language "LaTeX"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*latex\\s*$")
  (#set! injection.language "LaTeX"))

; less -> LESS
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*less\\s*$")
  (#set! injection.language "LESS"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*less\\s*$")
  (#set! injection.language "LESS"))

; log -> Log
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*log\\s*$")
  (#set! injection.language "Log"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*log\\s*$")
  (#set! injection.language "Log"))

; lua -> Lua
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*lua\\s*$")
  (#set! injection.language "Lua"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*lua\\s*$")
  (#set! injection.language "Lua"))

; make -> Makefile
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*make\\s*$")
  (#set! injection.language "Makefile"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*make\\s*$")
  (#set! injection.language "Makefile"))

; makefile -> Makefile
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*makefile\\s*$")
  (#set! injection.language "Makefile"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*makefile\\s*$")
  (#set! injection.language "Makefile"))

; markdown -> Markdown
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*markdown\\s*$")
  (#set! injection.language "Markdown"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*markdown\\s*$")
  (#set! injection.language "Markdown"))

; math -> Markdown
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*math\\s*$")
  (#set! injection.language "Markdown"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*math\\s*$")
  (#set! injection.language "Markdown"))

; objc -> Objective-C
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*objc\\s*$")
  (#set! injection.language "Objective-C"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*objc\\s*$")
  (#set! injection.language "Objective-C"))

; objcpp -> Objective-C++
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*objcpp\\s*$")
  (#set! injection.language "Objective-C++"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*objcpp\\s*$")
  (#set! injection.language "Objective-C++"))

; perl -> Perl
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*perl\\s*$")
  (#set! injection.language "Perl"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*perl\\s*$")
  (#set! injection.language "Perl"))

; php -> PHP
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*php\\s*$")
  (#set! injection.language "PHP"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*php\\s*$")
  (#set! injection.language "PHP"))

; pip -> Pip Requirements
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*pip\\s*$")
  (#set! injection.language "Pip Requirements"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*pip\\s*$")
  (#set! injection.language "Pip Requirements"))

; powerfx -> JavaScript
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*powerfx\\s*$")
  (#set! injection.language "JavaScript"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*powerfx\\s*$")
  (#set! injection.language "JavaScript"))

; powershell -> PowerShell
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*powershell\\s*$")
  (#set! injection.language "PowerShell"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*powershell\\s*$")
  (#set! injection.language "PowerShell"))

; properties -> Properties
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*properties\\s*$")
  (#set! injection.language "Properties"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*properties\\s*$")
  (#set! injection.language "Properties"))

; py -> Python
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*py\\s*$")
  (#set! injection.language "Python"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*py\\s*$")
  (#set! injection.language "Python"))

; python -> Python
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*python\\s*$")
  (#set! injection.language "Python"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*python\\s*$")
  (#set! injection.language "Python"))

; r -> R
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*r\\s*$")
  (#set! injection.language "R"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*r\\s*$")
  (#set! injection.language "R"))

; raku -> Raku
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*raku\\s*$")
  (#set! injection.language "Raku"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*raku\\s*$")
  (#set! injection.language "Raku"))

; razor -> Razor
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*razor\\s*$")
  (#set! injection.language "Razor"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*razor\\s*$")
  (#set! injection.language "Razor"))

; regex -> Regex
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*regex\\s*$")
  (#set! injection.language "Regex"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*regex\\s*$")
  (#set! injection.language "Regex"))

; requirements -> Pip Requirements
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*requirements\\s*$")
  (#set! injection.language "Pip Requirements"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*requirements\\s*$")
  (#set! injection.language "Pip Requirements"))

; rst -> reStructuredText
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*rst\\s*$")
  (#set! injection.language "reStructuredText"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*rst\\s*$")
  (#set! injection.language "reStructuredText"))

; ruby -> Ruby
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*ruby\\s*$")
  (#set! injection.language "Ruby"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*ruby\\s*$")
  (#set! injection.language "Ruby"))

; rust -> Rust
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*rust\\s*$")
  (#set! injection.language "Rust"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*rust\\s*$")
  (#set! injection.language "Rust"))

; scss -> SCSS
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*scss\\s*$")
  (#set! injection.language "SCSS"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*scss\\s*$")
  (#set! injection.language "SCSS"))

; shaderlab -> ShaderLab
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*shaderlab\\s*$")
  (#set! injection.language "ShaderLab"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*shaderlab\\s*$")
  (#set! injection.language "ShaderLab"))

; shell -> Shell Script
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*shell\\s*$")
  (#set! injection.language "Shell Script"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*shell\\s*$")
  (#set! injection.language "Shell Script"))

; sql -> SQL
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*sql\\s*$")
  (#set! injection.language "SQL"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*sql\\s*$")
  (#set! injection.language "SQL"))

; swift -> Swift
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*swift\\s*$")
  (#set! injection.language "Swift"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*swift\\s*$")
  (#set! injection.language "Swift"))

; tex -> TeX
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*tex\\s*$")
  (#set! injection.language "TeX"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*tex\\s*$")
  (#set! injection.language "TeX"))

; ts -> TypeScript
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*ts\\s*$")
  (#set! injection.language "TypeScript"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*ts\\s*$")
  (#set! injection.language "TypeScript"))

; tsx -> TSX
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*tsx\\s*$")
  (#set! injection.language "TSX"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*tsx\\s*$")
  (#set! injection.language "TSX"))

; typescript -> TypeScript
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*typescript\\s*$")
  (#set! injection.language "TypeScript"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*typescript\\s*$")
  (#set! injection.language "TypeScript"))

; vb -> Visual Basic
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*vb\\s*$")
  (#set! injection.language "Visual Basic"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*vb\\s*$")
  (#set! injection.language "Visual Basic"))

; xml -> XML
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*xml\\s*$")
  (#set! injection.language "XML"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*xml\\s*$")
  (#set! injection.language "XML"))

; xsl -> XSL
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*xsl\\s*$")
  (#set! injection.language "XSL"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*xsl\\s*$")
  (#set! injection.language "XSL"))

; yaml -> YAML
((comment) @_marker
  .
  (block_scalar) @injection.content
  (#match? @_marker "^#\\s*yaml\\s*$")
  (#set! injection.language "YAML"))

((comment) @_marker
  .
  (block_mapping_pair
    value: (block_node
      (block_scalar) @injection.content))
  (#match? @_marker "^#\\s*yaml-embedded-languages\\s*:\\s*yaml\\s*$")
  (#set! injection.language "YAML"))
